branch-defaults:
  master:
    environment: BoraApi-env
environment-defaults:
  BoraApi-env:
    branch: null
    repository: null
global:
  application_name: bora-api
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:sa-east-1::platform/Node.js running on
    64bit Amazon Linux/4.14.1
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
